name: CI

on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install pnpm 10.12.1
        uses: pnpm/action-setup@v3
        with:
          version: 10.12.1

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test:run

      - name: Build
        run: pnpm run build
